version: '3.8'

services:
  crocodileua-bot:
    build:
      context: ./
      cache_from:
        - kraftwerk28/crocodileua-bot
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: kraftwerk28/crocodileua-bot
    environment:
      NODE_ENV: 'production'
    env_file: ./.env.prod
    ports:
      - '1493:8080'
    restart: always

networks:
  default:
    name: globalpg
    external: true
