name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - uses: actions/checkout@v2

      - name: Create .env
        run:
          echo "${{ secrets.ENV }}" > .env.prod

      - name: Build image
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker-compose pull
          docker-compose build
          docker-compose push

      # - name: Deploy
        # env:
          # DOCKER_HOST: "ssh://${{ secrets.SSH_HOST }}"
        # run: |
          # echo "DOCKER_HOST: $DOCKER_HOST"
          # docker-compose build
