name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          # known_hosts: ${{ secrets.KNOWN_HOSTS }}

      # - uses: actions/checkout@v2

      - name: Check if ssh works
        env:
          DOCKER_HOST: ${{ secrets.SSH_HOST }}
        run: |
          echo "DOCKER_HOST: $DOCKER_HOST"
          docker ps
